### ISSUE TITLE
Greenhouse crop

### ISSUE THREAD

**Issue by atomao** [greenpeer/GreenLightPlus#2]
Hi, I was searching for what crop this simulation code works. Nowhere we don't specify crop, and from code I found tomato specified only in one docstring, is it right? Also can you suggest how we can use code for other crops?

**Comment by greenpeer** [comment]
Thank you for your question! The model currently defaults to tomatoes, but it can be defined for other crops as well. The goal is not to be specific to any one crop, but rather to design a universal model.
To use this code for other crops, you'll need to adjust the following aspects:

1.In create_green_light_model/set_gl_aux.py, locate the functions that define crop growth and development characteristics, and replace them with corresponding values for your target crop.
2.Growth stages: If the new crop has different growth stages from the current model, you may need to modify the logic related to growth stages.
3.Environmental responses: Ensure that the environmental response functions in the model (such as responses to temperature and light) are applicable to the new crop, and adjust them if necessary.

In the near future, I plan to extract the part for specifying and modifying crop models into a separate module to facilitate further development. I hope this information is helpful to you!

**Comment by greenpeer** [comment]
Thank you for your question! 

The model currently defaults to tomatoes, but it can be defined for other crops as well. The goal is not to be specific to any one crop, but rather to design a universal model.

To use this code for other crops, you'll need to adjust the following aspects:

1. In `create_green_light_model/set_gl_aux.py`, locate the functions that define crop growth and development characteristics, and replace them with corresponding values for your target crop.

2. **Growth stages**: If the new crop has different growth stages from the current model, you may need to modify the logic related to growth stages.

3. **Environmental responses**: Ensure that the environmental response functions in the model (such as responses to temperature and light) are applicable to the new crop, and adjust them if necessary.

In the near future, I plan to extract the part for specifying and modifying crop models into a separate module to facilitate further development. 

I hope this information is helpful to you!

**Comment by atomao** [comment]
HI, thank you for your response, waiting for separate module, closing the issue.
