### ISSUE TITLE
Alternative Package Installation Not Working

### ISSUE THREAD

**Issue by gsoykan** [greenpeer/GreenLightPlus#4]
The alternative package installation method described [here](https://botanicbyte.com/Tutorial/Installation#12-installing-from-github-clone) does not seem to work. 

**Possible Reason:**

It appears that the repository is missing necessary setup files. 

**Request:**

Including the appropriate setup files would facilitate contributing to the library and allow for a more flexible installation process. This would be beneficial for developers looking to work directly from the cloned repository.

Thank you for your attention to this matter.

**Comment by greenpeer** [comment]
@gsoykan Thank you for bringing this to attention. The issue has been resolved.


A `pyproject.toml` configuration file has been added to the repository. This addition should address the installation problems you encountered.
